{% set version = "0.3-57" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-clue
  version: {{ version|replace("-", "_") }}

source:
  fn: clue_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/clue_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/clue/clue_{{ version }}.tar.gz
  sha256: 6e369d07b464a9624209a06b5078bf988f01f7963076e946649d76aea0622d17

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-cluster

  run:
    - r-base
    - r-cluster

test:
  commands:
    - $R -e "library('clue')"  # [not win]
    - "\"%R%\" -e \"library('clue')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=clue
  license: GPL-2
  summary: CLUster Ensembles.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
