{% set version = "0.3-63" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-clue
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/clue_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/clue/clue_{{ version }}.tar.gz
  sha256: d913283c258a74bfdf95fb4c82b55d548829b0d650ce6824689d853c96138030

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-cluster                  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-cluster
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cluster

test:
  commands:
    - $R -e "library('clue')"           # [not win]
    - "\"%R%\" -e \"library('clue')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=clue
  license: GPL-2.0-only
  summary: CLUster Ensembles.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
