appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 7tiG41KCZRXBNwg8/u84FZ/nVXDBsZ4U/ngKFlTMW5ht1/L+sMMZMZ/kwSs+cjRbIRBJEmqtFX5u8oncHPp9Ofl6HYZiYGrMC2ATT9Hm0KmQ3IoQjonlD8UMOjfNNe+bYzWXP8QECiq+o53E/0LcbjkAh1Gh1zv3+b5s1F6r8/jNKjWezcRapISH1J3+MwLNHz7GaVa1GjIsnme3XvJSruOoV5t7bqt12GTG4RwzzxcVOcBCuQubuanaGiMffWqLOMQwVMVSriY01xlemCl1R1On0fuzLDzK70Yt2L8eBRcZ4DEdBJJBUsL4JUOTqo6tVOhO/Ggy57qbhQtXetAvb5JAEAxFWRrtpevfsTiCoWbNcUtkpHcmYicUYgs3X0kr8dk13ZacHLIA1Gdf2f0nl9bPLQAGrmJPcHG4KXA94Fw4+QOW2AjTCWTzH32dhfBvHEt2DC7MsE5rqGLdocQtLYEy+9/cXZugvmbGLlX6idPzduPuUh/JTXtWLemzMv/Rh1SLSOM8GMV6sLbOh8F59yvuJwHcvGy8EKwQVSmo+wDrwLpS0tdNRBKFTt/60LyCzkSZqCMBDazjuWvdZ6Qlx81t0xH96BOKzCI/TZH3OkK8vH6GrlyXrUAfIQDrU2lQpOh348/AxRgNP7Y70op4hlEZZs/zxDNkg0xfWRPv2PQ=}
